#  Template .NET Core build

#  This template allows you to validate your .NET Core package.
#  The workflow allows running tests and code linting on the default branch.

# To run your pipeline on a Windows machine, create a self-hosted Windows runner.
# For instructions on setting up a Windows runner, see https://support.atlassian.com/bitbucket-cloud/docs/set-up-runners-for-windows/

image: mcr.microsoft.com/dotnet/sdk:8.0

pipelines:
  custom:
    automated:
      - step:
          name: Setup .NET Build
          caches:
            - dotnetcore
          script:
            - echo "Starting build..."
            - dotnet restore
            - dotnet build --configuration Release

      - step:
          name: Steup Test Environment
          caches:
            - dotnetcore
            - chrome
            - chromedriver
          script:
            - apt-get update
            - apt-get install -y wget unzip

            # Verificando se o Chrome já está no cache
            - if [ ! -f "/usr/local/bin/chrome/google-chrome" ]; then
                wget -q https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb;
                apt install -y ./google-chrome-stable_current_amd64.deb;
                mkdir -p /usr/local/bin/chrome;
                mv /usr/bin/google-chrome /usr/local/bin/chrome/;
              fi
            
            # Verificando se o ChromeDriver já está no cache
            - if [ ! -f "/usr/local/bin/chromedriver-cache/chromedriver" ]; then
                wget -q https://storage.googleapis.com/chrome-for-testing-public/129.0.6668.100/linux64/chromedriver-linux64.zip;
                unzip chromedriver-linux64.zip;
                mkdir -p /usr/local/bin/chromedriver-cache;
                mv chromedriver /usr/local/bin/chromedriver-cache/;
                chmod +x /usr/local/bin/chromedriver-cache/chromedriver;
              fi
      
      - step:
          name: Run UI Tests
          caches:
            - dotnetcore
            - chrome
            - chromedriver
          script:
            - ln -s /usr/local/bin/chrome/google-chrome /usr/bin/google-chrome
            - ln -s /usr/local/bin/chromedriver-cache/chromedriver /usr/local/bin/chromedriver

            - google-chrome --version
            - /usr/local/bin/chromedriver --version

            - export CHROMEDRIVER_PATH="/usr/local/bin"
            - mv chromedriver-linux64 $CHROMEDRIVER_PATH/chromedriver
            - chmod +x $CHROMEDRIVER_PATH/chromedriver
            - dotnet test --filter FullyQualifiedName~MeuClienteWebTestProject.PlanosTest

definitions:
  caches:
    dotnetcore: ~/.nuget/packages
    chrome: /usr/local/bin/chrome
    chromedriver: /usr/local/bin/chromedriver-cache