#  Template .NET Core build

#  This template allows you to validate your .NET Core package.
#  The workflow allows running tests and code linting on the default branch.

# To run your pipeline on a Windows machine, create a self-hosted Windows runner.
# For instructions on setting up a Windows runner, see https://support.atlassian.com/bitbucket-cloud/docs/set-up-runners-for-windows/

image: mcr.microsoft.com/dotnet/sdk:8.0
image: selenium/standalone-chrome:latest

pipelines:
  custom:
    automated:
      - step:
          name: Setup .NET Build
          caches:
            - dotnetcore
          script:
            - echo "Starting build..."
            - dotnet restore
            - dotnet build --configuration Release
     
      - step:
          name: Run UI Tests
          services:
            - selenium
          caches:
            - dotnetcore
          script:
            - google-chrome --version
            - chromedriver --version
            - dotnet test --filter FullyQualifiedName~MeuClienteWebTestProject.PlanosTest

definitions:
  caches:
    dotnetcore: ~/.nuget/packages